### ISSUE TITLE
not an issue - faulty ssd - [error] block 1346671 is not an object map block

### ISSUE THREAD

**Issue by johndpope** [tienex/apfs#3]
if I run 

./apfs_traverse -v /Volumes/ELEVATE/errorFree2.img
[device] block size = 4096 block count = 244059313
[info] selected checkpoint xid 407801
[error] block 1346671 is not an object map block
error: cannot open volume #0

When I run 
./nx_scavenge /Volumes/ELEVATE/errorFree2.img
It spews out a bunch of candidate blocks
Candidate Block 2212368 (0x21c210): Checksum = 0xc5afa958850bf5d9 Object ID = 461635 (0x70b43) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212369 (0x21c211): Checksum = 0x4c27d44dd7d0e737 Object ID = 461637 (0x70b45) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212370 (0x21c212): Checksum = 0x5fb876c76d81f75a Object ID = 522561 (0x7f941) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212371 (0x21c213): Checksum = 0x76e8e18daefb0deb Object ID = 461266 (0x709d2) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212372 (0x21c214): Checksum = 0x5c25bd0aeb8f7668 Object ID = 461289 (0x709e9) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212373 (0x21c215): Checksum = 0x7d3cd4937176dee7 Object ID = 461269 (0x709d5) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212374 (0x21c216): Checksum = 0x8257a58b491299d1 Object ID = 461286 (0x709e6) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212375 (0x21c217): Checksum = 0xc0adb4fde9b7150d Object ID = 461510 (0x70ac6) Checkpoint ID = 38030 (0x948e) Type = 3.14 [apfs root: btree node]
Candidate Block 2212376 (0x21c218): Checksum = 0x30ff1606db6f6420 Object ID = 2212376 (0x21c218) Checkpoint ID = 38030 (0x948e) Type = 3.11 [object map: btree node]

Do you have any pointers on how to get around bad blocks? I have ran disk drill across drive - and it can find files - but throws them into buckets -  I was hoping to roll back apfs checkpoints to a previous state and recover directory structure.

**Comment by tienex** [comment]
Hey, you can try apfs_traverse -f to select the first (oldest) xid, or -x <xid> and see if it may point to a valid object map connected to the transaction id selected, at the moment i can't help more 'cause i'm not at my computer. I'll be around tomorrow.

**Comment by tienex** [comment]
-x XID, sorry, formatting issue.

**Comment by johndpope** [comment]
managed to recover lost partition on drive using iBoySoft. thanks
